# ===== [00] BUILD SYSTEM =====================================================
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

# ===== [01] PROJECT METADATA ================================================
[project]
name = "my-ai-teacher"
version = "0.1.0"
requires-python = ">=3.10,<4.0"
description = "Clean scaffold for AI Teacher (Streamlit + RAG)"
readme = "README.md"
authors = [{ name = "you" }]

# ===== [02] RUNTIME DEPS =====================================================
dependencies = [
  "streamlit>=1.32",
  "pydantic>=2,<3",
  "pydantic-settings>=2,<3",
  "llama-index-core>=0.10",
  "google-api-python-client>=2.136.0",
  "google-auth>=2.30.0",
  "pypdf>=4.2,<5",            # ← PDF 텍스트 추출용 (신규 추가)
]

# ===== [03] DEV DEPS (optional) =============================================
[project.optional-dependencies]
dev = [
  "mypy>=1.7",
  "ruff>=0.5",
  "bandit>=1.7",
  "pytest>=8",
  "types-requests",
  "types-PyYAML",
]

# ===== [04] TOOL CONFIG POINTERS ============================================
[tool.ruff]
extend = "ruff.toml"

[tool.mypy]
config_file = "mypy.ini"

# ===== [05] SETUPTOOLS (package discovery) ==================================
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

# ===== [06] POETRY SETUP (disable package install of the app) ===============
[tool.poetry]
package-mode = false
