# [01] START: .github/ISSUE_TEMPLATE/docs.yml
name: "Docs"
description: "문서 개선"
labels: ["docs"]
body:
  - type: dropdown
    id: doc_area
    attributes:
      label: 문서 영역
      options:
        - README
        - CONVENTIONS
        - CHANGELOG
        - GPT Docs Index
        - 기타
    validations:
      required: true
  - type: textarea
    id: change
    attributes:
      label: 수정 제안
      description: 변경 전/후를 비교해서 간단히 적어 주세요.
# [01] END: .github/ISSUE_TEMPLATE/docs.yml
