# ===== [01] FILE: .github/workflows/_paths_filter.yml — START =====
name: _paths_filter

on:
  workflow_call:
    inputs:
      filters:
        description: "Optional: custom filters (YAML text or path). If omitted, uses defaults below."
        required: false
        type: string
      base:
        description: "Base ref to compare (default: PR base or origin/main)"
        required: false
        type: string
      ref:
        description: "Ref/SHA to compare against (default: current SHA)"
        required: false
        type: string
    # NOTE: Do NOT declare 'GITHUB_TOKEN' here. It's a system-reserved secret automatically provided.

    outputs:
      python_changed:
        description: "True if Python files changed"
        value: ${{ jobs.paths.outputs.python_changed }}
      workflows_changed:
        description: "True if workflow files changed"
        value: ${{ jobs.paths.outputs.workflows_changed }}
      docs_changed:
        description: "True if docs changed"
        value: ${{ jobs.paths.outputs.docs_changed }}
      python_files:
        description: "List of changed Python files"
        value: ${{ jobs.paths.outputs.python_files }}
      workflows_files:
        description: "List of changed workflow files"
        value: ${{ jobs.paths.outputs.workflows_files }}
      docs_files:
        description: "List of changed docs files"
        value: ${{ jobs.paths.outputs.docs_files }}

permissions:
  contents: read
  pull-requests: read

jobs:
  paths:
    runs-on: ubuntu-latest

    outputs:
      python_changed:    ${{ steps.filter.outputs.python }}
      workflows_changed: ${{ steps.filter.outputs.workflows }}
      docs_changed:      ${{ steps.filter.outputs.docs }}
      python_files:      ${{ steps.filter.outputs.python_files }}
      workflows_files:   ${{ steps.filter.outputs.workflows_files }}
      docs_files:        ${{ steps.filter.outputs.docs_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          # If caller doesn't set 'base' or 'ref', use sensible defaults
          base: ${{ inputs.base || (github.event.pull_request.base.sha || 'origin/main') }}
          ref:  ${{ inputs.ref  || github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }} # <-- use built-in reserved token; DO NOT redeclare in workflow_call
          # If caller passes a custom 'filters' (YAML string or a file path), use it; otherwise, use defaults.
          filters: ${{ inputs.filters }}
          default: |
            python:
              - '**/*.py'
            workflows:
              - '.github/workflows/**/*.yml'
              - '.github/workflows/**/*.yaml'
            docs:
              - 'docs/**'
              - '**/*.md'
# ===== [01] FILE: .github/workflows/_paths_filter.yml — END =====
