name: _paths_filter

on:
  workflow_call:
    inputs:
      filters:
        required: true
        type: string
      base:
        required: false
        type: string
      ref:
        required: false
        type: string
    outputs:
      python_changed:   { value: ${{ jobs.paths.outputs.python_changed }} }
      workflows_changed:{ value: ${{ jobs.paths.outputs.workflows_changed }} }
      docs_changed:     { value: ${{ jobs.paths.outputs.docs_changed }} }
      python_files:     { value: ${{ jobs.paths.outputs.python_files }} }
      workflows_files:  { value: ${{ jobs.paths.outputs.workflows_files }} }
      docs_files:       { value: ${{ jobs.paths.outputs.docs_files }} }
    secrets:
      GITHUB_TOKEN: { required: true }

permissions:
  contents: read

jobs:
  paths:
    runs-on: ubuntu-latest
    outputs:
      python_changed:    ${{ steps.filter.outputs.python }}
      workflows_changed: ${{ steps.filter.outputs.workflows }}
      docs_changed:      ${{ steps.filter.outputs.docs }}
      python_files:      ${{ steps.filter.outputs.python_files }}
      workflows_files:   ${{ steps.filter.outputs.workflows_files }}
      docs_files:        ${{ steps.filter.outputs.docs_files }}
    steps:
      # 1) 루트에 .git 보장 + 전체 이력(비교/머지 검사용)
      - name: Checkout (root, full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true

      # 2) git 128 예방(dubious ownership 방지)
      - name: Mark repo as safe for git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # 3) dorny 실행(base/ref 명시)
      - name: Paths filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ${{ inputs.base || (github.event_name == 'pull_request' && github.event.pull_request.base.sha) || 'refs/heads/main' }}
          ref:  ${{ inputs.ref  || (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}
          list-files: json
          filters: ${{ inputs.filters }}
