# [04] START: .github/workflows/canon-validate.yml
name: Canon Validate

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  canon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (pyyaml)
        run: |
          python -m pip install --upgrade pip
          python -m pip install pyyaml

      - name: Validate _canon.yaml
        run: |
          python tools/validate_canon.py
# [04] END: .github/workflows/canon-validate.yml
