# [12] START: .github/workflows/coverage.yml
name: Test Coverage Gate

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov

      - name: Run tests with coverage (src/)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest -q --cov=src --cov-report=xml

      - name: Enforce minimum coverage (>= 70%)
        env:
          COVERAGE_MIN: "0.70"
        run: |
          python tools/check_coverage.py

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
# [12] END: .github/workflows/coverage.yml
