name: Publish Prompts

on:
  workflow_dispatch:
    inputs:
      prompts_yaml:
        description: "Prompts YAML (version + modes only)"
        required: false
        default: ""
  repository_dispatch:
    types: [publish-prompts]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create prompts.yaml from inputs/payload or fallback
        id: mk
        shell: bash
        run: |
          set -euo pipefail
          PY=$(mktemp)
          cat > "$PY" <<'PYCODE'
          import os, sys, json, yaml, pathlib
          ev = json.loads(os.getenv('GITHUB_EVENT', '{}'))
          # 1) inputs.prompts_yaml (workflow_dispatch)
          txt = (ev.get('inputs') or {}).get('prompts_yaml') or ''
          # 2) client_payload.prompts_yaml (repository_dispatch)
          if not txt:
              txt = (ev.get('client_payload') or {}).get('prompts_yaml') or ''
          # 3) fallback 파일(있으면)
          if not txt:
              for cand in ('release/assets/prompts.yaml','assets/prompts.yaml','prompts.yaml'):
                  p = pathlib.Path(cand)
                  if p.exists():
                      txt = p.read_text(encoding='utf-8')
                      break
          # 안전 가드
          y = yaml.safe_load(txt) if txt.strip() else {}
          if not isinstance(y, dict) or 'modes' not in y:
              raise SystemExit("invalid or empty prompts YAML (need object with 'modes')")
          pathlib.Path("dist").mkdir(exist_ok=True)
          pathlib.Path("dist/prompts.yaml").write_text(yaml.safe_dump(y, allow_unicode=True, sort_keys=False), encoding="utf-8")
          print("created: dist/prompts.yaml")
          PYCODE
          python "$PY"

      - name: Validate schema (if project validator exists)
        shell: bash
        run: |
          set -euo pipefail
          if [ -f scripts/validate_prompts.py ]; then
            python scripts/validate_prompts.py "dist/prompts.yaml"
          else
            echo "no project validator; basic validation already done."
          fi

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: prompts
          path: dist/prompts.yaml
