name: Publish Prompts

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/_gpt/**'  # SSOT 루트 변경 시만 트리거 (Workspace Pointer 기준)

permissions:
  contents: read

concurrency:
  group: publish-prompts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 스텝 1) prompts.yaml을 "파일"로 만들어 outputs로 경로만 전달
      - name: Build prompts.yaml
        id: build
        shell: bash
        run: |
          set -euo pipefail

          out="${RUNNER_TEMP}/prompts.yaml"

          # 1순위: 저장소의 빌드 스크립트가 있으면 그 결과를 사용
          if [[ -x "./scripts/build-prompts-yaml.sh" ]]; then
            ./scripts/build-prompts-yaml.sh > "$out"
          # 2순위: SSOT에 직접 커밋된 prompts.yaml 사용
          elif [[ -f "docs/_gpt/prompts.yaml" ]]; then
            cp "docs/_gpt/prompts.yaml" "$out"
          else
            echo "Error: could not find scripts/build-prompts-yaml.sh or docs/_gpt/prompts.yaml" >&2
            exit 1
          fi

          # 내용 검증(빈 파일 금지)
          if [[ ! -s "$out" ]]; then
            echo "Error: prompts.yaml is empty." >&2
            exit 1
          fi

          # 다음 스텝으로 "경로"만 안전하게 전달
          printf 'prompts_yaml_path=%s\n' "$out" >> "$GITHUB_OUTPUT"

      # 스텝 2) 게시 — 파일 경로를 env로 주입하고, 내용은 같은 스텝에서 export
      - name: Publish prompts
        env:
          PROMPTS_YAML_PATH: ${{ steps.build.outputs.prompts_yaml_path }}
        shell: bash
        run: |
          set -euo pipefail

          # 필수 입력 확인(set -u 안전 패턴)
          : "${PROMPTS_YAML_PATH:?No prompts_yaml provided}"

          # 일부 스크립트가 PROMPTS_YAML "내용"을 기대하는 경우를 위해 export
          export PROMPTS_YAML="$(cat "$PROMPTS_YAML_PATH")"

          # 이중 검증(빈 내용 금지)
          if [[ -z "${PROMPTS_YAML-}" ]]; then
            echo "Error: No prompts_yaml provided." >&2
            exit 1
          fi

          # 게시 스크립트 실행(가능하면 표준입력으로도 전달)
          if [[ -x "./scripts/publish-prompts.sh" ]]; then
            ./scripts/publish-prompts.sh <<< "$PROMPTS_YAML"
          else
            echo "Error: ./scripts/publish-prompts.sh not found or not executable." >&2
            exit 1
          fi
