name: Publish Prompts

on:
  workflow_dispatch:
    inputs:
      prompts_yaml:
        description: "YAML payload (persona + modes)"
        required: false
  repository_dispatch:
    types: [publish-prompts]

permissions:
  contents: write  # 릴리스 생성/업데이트에 필요

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # payload를 안전하게 파일로 저장 (JS로 처리: 셸 quoting 이슈 차단)
      - name: Write prompts.yaml from payload
        id: write
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const isWD = (context.eventName === 'workflow_dispatch');
            const data = isWD
              ? (core.getInput('prompts_yaml') || '')
              : ((context.payload.client_payload && context.payload.client_payload.prompts_yaml) || '');
            fs.mkdirSync('release/assets', { recursive: true });
            fs.writeFileSync('release/assets/prompts.yaml', data, { encoding: 'utf8' });
            core.setOutput('size', String(data.length));

      - name: Show payload size
        run: echo "payload_size=${{ steps.write.outputs.size }}"

      - name: Validate schema (if repo has validator)
        run: |
          if [ -f scripts/validate_prompts.py ]; then
            python scripts/validate_prompts.py "release/assets/prompts.yaml"
          else
            echo "No validator script found. Skipping strict validation."
          fi

      # 최신 릴리스 태그 prompts-latest 로 파일 첨부/갱신
      - name: Upload to GitHub Release (tag=prompts-latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prompts-latest
          name: Prompts Latest
          files: release/assets/prompts.yaml
          make_latest: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
