# [WF-PROMPTS] START: .github/workflows/publish-prompts.yml
name: Publish Prompts

on:
  workflow_dispatch:
    inputs:
      prompts_yaml:
        description: "Prompts YAML (optional)"
        required: false
        type: string
  repository_dispatch:
    types: [publish-prompts]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (PyYAML)
        shell: bash
        run: |
          set -Eeuo pipefail
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Ensure prompts.yaml (input or repo file)
        id: ensure
        shell: bash
        run: |
          set -Eeuo pipefail
          INPUT="${{ github.event.inputs.prompts_yaml || github.event.client_payload.prompts_yaml || '' }}"
          if [[ -n "$INPUT" ]]; then
            printf "%s" "$INPUT" > prompts.yaml
            echo "from=input" >> "$GITHUB_OUTPUT"
          elif [[ -f prompts.yaml ]]; then
            echo "from=repo" >> "$GITHUB_OUTPUT"
          else
            echo "::error ::prompts.yaml not provided and not found in repo"
            exit 1
          fi
          ls -l prompts.yaml

      - name: Normalize prompts.yaml (schema-compat)
        run: python .github/scripts/normalize_prompts_yaml.py prompts.yaml

      - name: Validate schema
        run: python scripts/validate_prompts.py "prompts.yaml"

      - name: Build composite prompts (A‑a/b/c)
        shell: bash
        run: |
          set -Eeuo pipefail
          python .github/scripts/build_prompts_full.py

      - name: Upload release (tag: prompts-latest)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: prompts-latest
          make_latest: true
          files: |
            prompts.yaml
            prompts_full/*.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# [WF-PROMPTS] END
