# [01] START: .github/workflows/rag-tests.yml — RAG 서브셋 테스트 (pytest 설치 보장)
name: rag-tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**"
      - "tests/**"
      - "docs/_gpt/**"
      - ".github/workflows/rag-tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies (robust)
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          # 있는 파일부터 설치: dev -> prod -> editable project
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e . || true; fi
          # 최후방어: pytest/pytest-cov/PyYAML을 강제 설치
          pip install "pytest>=7" "pytest-cov>=4" "pyyaml>=6"

      - name: Run subset tests for RAG
        run: |
          python -m pytest -q -k "rag_engine_toggle or rag_engine_bm25"

# [01] END: .github/workflows/rag-tests.yml
