name: Release

on:
  push:
    tags:
      - "v*.*.*"        # 예: v1.2.3
  workflow_dispatch:

permissions:
  contents: write   # 릴리스 작성에 필요

jobs:
  build-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Zip artifact
        run: |
          mkdir -p dist
          zip -r dist/maic-${GITHUB_REF_NAME}.zip . -x ".git/*" ".github/*" "__pycache__/*" ".venv/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/maic-${{ github.ref_name }}.zip
          generate_release_notes: true
