# ===== [00] META =============================================================  # [00] START
name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g., v1.2.3)"
        required: true
permissions:
  contents: write
concurrency:
  group: release-${{ github.ref }}

jobs:
  build:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.ver.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            pyproject.toml

      - name: Show tool versions
        run: |
          python -V
          pip -V
          git rev-parse --short HEAD

      - name: Resolve version
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          if [ -n "${{ github.event.inputs.version }}" ]; then
            TAG="${{ github.event.inputs.version }}"
          else
            TAG="${GITHUB_REF_NAME}"
          fi
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build dist
        run: |
          python -m build
          ls -lh dist/

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/*
# [00] END

# [02] START
  publish:
    name: Publish GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.ver.outputs.tag }}
          name: Release ${{ steps.ver.outputs.tag }}
          prerelease: false
          generate_release_notes: true
          files: |
            dist/maic-${{ steps.ver.outputs.tag }}.zip
            dist/maic-${{ steps.ver.outputs.tag }}.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# [02] END
