# [13] START: .github/workflows/security.yml
name: Security Scans

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-audit

      # requirements*.txt가 있으면 그 기준으로, 없으면 현재 환경 검사
      - name: Run pip-audit (requirements)
        if: ${{ hashFiles('**/requirements*.txt') != '' }}
        run: |
          pip-audit -r requirements.txt

      - name: Run pip-audit (environment)
        if: ${{ hashFiles('**/requirements*.txt') == '' }}
        run: |
          pip-audit

  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --redact
# [13] END: .github/workflows/security.yml
