# File: .github/workflows/security.yml
# ===================== [01] Security Scans — START =====================
name: CI • Security

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # (args 미지원 이슈로 기본 스캔 설정 사용)
# ===================== [01] Security Scans — END =======================
