# [06] START: .github/workflows/security.yml
name: CI • Security Scans

on:
  pull_request:
  push:
    branches: ["**"]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit bandit

      - name: pip-audit (dependencies)
        run: |
          pip install .[dev]
          pip-audit

      - name: bandit (SAST)
        run: |
          bandit -r -q -x tests .

      - name: gitleaks (secrets)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# [06] END: .github/workflows/security.yml
