# [13] START: .github/workflows/security.yml
name: Security Scans

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          python -m pip install pip-audit

      - name: Run pip-audit (requirements)
        if: ${{ hashFiles('**/requirements*.txt') != '' }}
        run: |
          pip-audit -r requirements.txt

      - name: Run pip-audit (environment)
        if: ${{ hashFiles('**/requirements*.txt') == '' }}
        run: |
          pip-audit

  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout (full history recommended)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 조직 계정이 아닌 개인 계정(repo owner가 개인)인 경우 라이선스 불필요
          # GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
# [13] END: .github/workflows/security.yml
