[server]
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false
showEmailPrompt = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#5e6ad2"
backgroundColor = "#08090a"
secondaryBackgroundColor = "#1c1c1f"
textColor = "#f7f8f8"