[server]
headless = false
enableCORS = false
enableXsrfProtection = false
showEmailPrompt = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
primaryColor = "#5e6ad2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1a1a1a"

[client]
showErrorDetails = true