# Streamlit Secrets Example
# 주의: 이 파일은 예시입니다. 실제 시크릿은 GitHub Secrets/Actions 또는 Streamlit Cloud에 등록하세요.
# 값 입력 시, 멀티라인/JSON/키 재사용이 필요한 경우 트리플 싱글쿼트(''' ... ''') 사용을 권장합니다.

[drive]
# Google Drive prepared 폴더 ID (SSOT)
prepared_folder_id = '''1bltOvqYsifPtmcx-epwJTq-hYAklNp2j'''

[service_account]  # (선택) GCP 서비스 계정 키를 JSON 통째로 보관해야 할 경우
# 주의: 로컬/레포에 실제 키를 커밋하지 마세요.
# 예시:
# json = '''
# {
#   "type": "service_account",
#   "project_id": "your-project",
#   "private_key_id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
#   "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
#   "client_email": "svc@your-project.iam.gserviceaccount.com",
#   "client_id": "1234567890",
#   "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#   "token_uri": "https://oauth2.googleapis.com/token",
#   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/svc%40your-project.iam.gserviceaccount.com"
# }
# '''

[app]
# 안전 가드레일: 앱은 반드시 시크릿에서 값을 읽고, 하드코딩을 금지합니다.
# 예) os.environ / st.secrets / GitHub Actions vars를 통해 주입
require_secrets = true
