########################################################
# UI 설정
########################################################
APP_ADMIN_PASSWORD = "0000"         # TODO: 운영 전 강한 비밀번호로 교체 권장
DISABLE_BG = "false"

########################################################
# GitHub — SSOT(쓰기/버전) & 런타임 로더
# - 런타임 로더(load_prompts)는 MAIC_GH_* 변수를 사용합니다.
# - Admin UI는 GITHUB_*를 사용해 publish-prompts 워크플로를 호출합니다.
########################################################
# (런타임 로더용)
MAIC_GH_OWNER = "LEES1605"
MAIC_GH_REPO  = "MAIC"
MAIC_PROMPTS_TAG   = "prompts-latest"
MAIC_PROMPTS_ASSET = "prompts.yaml"

# (Admin UI용)
GITHUB_TOKEN    = '''ghp*******************************************************'''
GITHUB_REPO     = "LEES1605/MAIC"
GITHUB_BRANCH   = "main"
GITHUB_WORKFLOW = "publish-prompts.yml"   # 워크플로 파일명

########################################################
# LLM / 임베딩 키
########################################################
GEMINI_MODEL   = "gemini-1.5-flash"
GEMINI_API_KEY = "****************************************-****************************************"

OPENAI_MODEL   = "gpt-4o-mini"
OPENAI_API_KEY = "sk-****************************************-***************************************"

########################################################
# Google Drive (서비스 계정 방식만 사용) — RAG 등 '읽기 전용'에만 사용
# ⚠️ 프롬프트 배포/로딩에는 더 이상 사용하지 않습니다(GitHub Releases로 대체).
########################################################
GDRIVE_AUTH_MODE = "service_account"
GDRIVE_SCOPES = '["https://www.googleapis.com/auth/drive.readonly","https://www.googleapis.com/auth/drive.metadata.readonly"]'

# (다른 기능에서 쓸 수 있는 폴더 ID는 유지)
GDRIVE_PREPARED_FOLDER_ID = "1bltOvqYsifPtmcx-epwJTq-hYAklNp2j"
GDRIVE_BACKUP_FOLDER_ID   = "1ACOkcpj7Jhnhtt2svVY9o6kJqRSAdll7"

# ✅ 프롬프트 전용 ID는 제거했습니다.
# MAIC_PROMPTS_DRIVE_FOLDER_ID  ← 제거(더 이상 사용하지 않음)

# 서비스 계정(JSON) — 세 개의 작은따옴표 유지
gcp_service_account = '''{
  "type": "service_account",
  "project_id": "gen-lang-client-0788677923",
  "private_key_id": "a****************************************",
  "private_key": "-----BEGIN PRIVATE KEY-----\n****************************************\n-----END PRIVATE KEY-----\n",
  "client_email": "lees-grammar-teacher@gen-lang-client-0788677923.iam.gserviceaccount.com",
  "client_id": "108413140221233675842",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/lees-grammar-teacher%40gen-lang-client-0788677923.iam.gserviceaccount.com"
}'''
